In [3]:
import pandas as pd
fruits = pd.DataFrame({"Apples": [30], "Bananas": [21]})
fruits

   Apples  Bananas
0      30       21

In [ ]:
fruit_sales = pd.DataFrame({"Apples" : [35,41], "Bananas": [21,34]},index = ["2017 Sales", "2018 Sales"])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [10]:
import pandas as pd
ingredients = pd.Series(["4 cups","1 cup","2 large","1 can"], index = ["Flour", "Milk", "Eggs", "Spam"], name = "Dinner")
ingredients

#ingredients.loc["Flour"]

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [8]:
import pandas as pd
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

animals.to_csv('cows_and_goats.csv')

In [13]:
import pandas as pd
products = pd.read_csv("products.csv")
products.loc[[1,2,3,4]]
products.iloc[:4]

,Product ID,Product Name,Category,Price,Stock
0,P001,Wireless Bluetooth Headphones,Electronics,79.99,150
1,P002,Stainless Steel Water Bottle,Kitchen & Home,24.99,320
2,P003,Yoga Mat Pro,Sports & Fitness,45.00,200
3,P004,LED Desk Lamp,Office Supplies,34.50,180

In [12]:
import pandas as pd
products = pd.read_csv("products.csv")
# print(products)
products_count = products.Category.value_counts()
products_count

Category
Electronics          3
Kitchen & Home       3
Sports & Fitness     2
Office Supplies      2
Food & Beverages     1
Footwear             1
Home & Bath          1
Home Decor           1
Health & Wellness    1
Name: count, dtype: int64

In [ ]:
import pandas as pd
products = pd.read_csv("products.csv")
price_to_stock_serie = products.Price / products.Stock
max_product_idx = price_to_stock_serie.idxmax()

max_product_name = products.loc[max_product_idx, "Name"]
max_product_name

,Product ID,Name,Category,Price,Stock
0,P001,Wireless Bluetooth Headphones,Electronics,79.99,150
1,P002,Stainless Steel Water Bottle,Kitchen & Home,24.99,320
2,P003,Yoga Mat Pro,Sports & Fitness,45.00,200
3,P004,LED Desk Lamp,Office Supplies,34.50,180
4,P005,Organic Green Tea (100 bags),Food & Beverages,18.99,500
5,P006,Running Shoes - Men's,Footwear,95.00,75
6,P007,Laptop Stand Adjustable,Office Supplies,52.00,140
7,P008,Cotton Bath Towel Set,Home & Bath,39.99,260
8,P009,Portable Phone Charger 20000mAh,Electronics,49.99,110
9,P010,Non-stick Frying Pan 28cm,Kitchen & Home,29.99,190
10,P011,Resistance Bands Set,Sports & Fitness,22.50,350
11,P012,Scented Soy Candle,Home Decor,16.00,400
12,P013,Wireless Computer Mouse,Electronics,27.99,230
13,P014,Bamboo Cutting Board,Kitchen & Home,21.00,175
14,P015,Vitamin C Supplement 60 Tabs,Health & Wellness,14.99,600

In [18]:
import pandas as pd

df = pd.DataFrame({
    "Math" : [20, 30, 40, 50],
    "Science" : [1,2,3,4]
})

df["New_marks"] = df.apply(lambda data: data["Math"] + data["Science"], axis=1)
new = sum(df["Math"])
total = df.apply(max, axis=1)
df

   Math  Science  New_marks
0    20        1         21
1    30        2         32
2    40        3         43
3    50        4         54

In [39]:
# GroupBy()  ie. Split-Apply-Combine
# When you say groupBy("team"), here pandas will create a group by object where keys are the name of group and the values are the Dataframe with rows of each 
# {
#    "A": DataFrame_of_A_rows,
#    "B": DataFrame_of_B_rows
# }

import pandas as pd

team = pd.DataFrame({
    "teams":["A", "B", "A", "B", "A"],
    "points": [20,23,65,345,80],
    "marks": [34,90,87,25,45]
})
mean = team.groupby("teams").mean()
groups = team.groupby("teams")
groups.get_group("A")

teams_count = team.teams.value_counts()
teams_count2 = team.groupby('teams')["teams"].count()
teams_count2

teams
A    3
B    2
Name: teams, dtype: int64

In [31]:
import pandas as pd

reviews = pd.DataFrame({
    "country": ["France", "France","France","Italy", "Italy"],
    "province": ["Boardeaux", "Boardeaux", "Burgundy", "Tuscany", "Tuscany"],
    "winery": ["X", "Y", "Z", "A", "B"],
    "points": [90,95,92,91,97]
})

result = reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()]).reset_index(drop=True)
result
# When grouping by two columns we get a multi-indexed DF, we can use reset_index() to bring back the normal indices

C:\Users\HP\AppData\Local\Temp\ipykernel_17228\4294546212.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()]).reset_index(drop=True)

  country   province winery  points
0  France  Boardeaux      Y      95
1  France   Burgundy      Z      92
2   Italy    Tuscany      B      97

In [26]:
import pandas as pd

reviews = pd.DataFrame({
    "country": ["France", "France","France","Italy", "Italy"],
    "province": ["Boardeaux", "Boardeaux", "Burgundy", "Tuscany", "Tuscany"],
    "winery": ["X", "Y", "Z", "A", "B"],
    "points": [90,95,92,91,97]
})

aggrigate = reviews.groupby("country")['points'].agg([min,max]).reset_index()
aggrigate

C:\Users\HP\AppData\Local\Temp\ipykernel_17228\4247325747.py:10: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  aggrigate = reviews.groupby("country")['points'].agg([min,max]).reset_index()
C:\Users\HP\AppData\Local\Temp\ipykernel_17228\4247325747.py:10: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  aggrigate = reviews.groupby("country")['points'].agg([min,max]).reset_index()

  country  min  max
0  France   90   95
1   Italy   91   97

In [ ]:
import pandas as pd

reviews = pd.DataFrame({
    "country": ["France", "France","France","Italy", "Italy"],
    "province": ["Boardeaux", "Boardeaux", "Burgundy", "Tuscany", "Tuscany"],
    "winery": ["X", "Y", "Z", "A", "B"],
    "points": [90,95,92,91,97]
})

# reviews.sort_values('points', ascending=False)
reviews.sort_values(['points', 'winery'], ascending=False)

  country   province winery  points
0  France  Boardeaux      X      90
3   Italy    Tuscany      A      91
2  France   Burgundy      Z      92
1  France  Boardeaux      Y      95
4   Italy    Tuscany      B      97

In [74]:
import pandas as pd

reviews = pd.DataFrame({
    "country": ["France", "France","Rwanda","France","Italy", "Italy"],
    "province": ["Boardeaux", "Boardeaux", None, "Burgundy", "Tuscany", "Tuscany"],
    "winery": ["X", "Y", "Z","V", "A", "B"],
    "points": [90,95,92,91,97,88]
})
# reviews.province.fillna('Unknown')
# reviews[pd.isnull(reviews.province)]

reviews[reviews.province.notnull()]

  country   province winery  points
0  France  Boardeaux      X      90
1  France  Boardeaux      Y      95
3  France   Burgundy      V      91
4   Italy    Tuscany      A      97
5   Italy    Tuscany      B      88